### ISSUE TITLE
Graceful shutdown for node apps ...

### ISSUE THREAD

**Issue by iamjochem** [gitterHQ/shutdown#1]
hi there!

I've been searching for a generic shutdown module for my apps, although npm offers quite a few modules nothing really stands out in terms of popularity (stars) or usage/downloads, most projects have had no commits for a long time (by node module standards at least) and look to be a little to niave in their implementation.

I find this module to be the best of the bunch ... I was wondering whether you are still/currently using this module yourself  and/or whether you have any caveats with regard to usage?

thanks and regards.

**Comment by suprememoocow** [comment]
Hi @iamjochem. Sorry about the delay in getting back to you. 

All the Gitter services use it. It could certainly do with some maintenance (as demonstrated by the length of time it took for me to respond here) but it does what it needs to and generally works very well in our busy production environment.
